# Generated by Django 5.2.1 on 2025-06-03 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('USER', 'User')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='00000000', help_text='Required. Enter a unique ID number (digits only).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must contain only digits', regex='^[0-9]+$')]),
        ),
    ]
