# Generated by Django 5.2.1 on 2025-06-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_user_level_alter_customuser_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='item_barcodes/'),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
