# Generated by Django 4.2.7 on 2025-06-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_barcode_item_barcode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
