# Generated by Django 5.2.1 on 2025-06-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_minimum_stock_item_stock_quantity'),
    ]

    operations = [
    ]
