# Generated by Django 5.0.4 on 2025-06-21 08:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_company_branch_migration_fixed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['company', 'name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this user belongs to (for Managers and Users).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='api.branch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='00000000', help_text='Required. Enter a unique ID number (digits only, unique per branch).', max_length=20, validators=[django.core.validators.RegexValidator(message='ID number must contain only digits', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterModelTable(
            name='branch',
            table=None,
        ),
    ]
