# Generated by Django 5.0.4 on 2025-06-23 01:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_branch_options_transaction_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='company',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='global_user_level',
            field=models.CharField(choices=[('BOSS_DEVELOPER', 'Boss/Developer'), ('MEMBER', 'Member')], default='MEMBER', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='00000000', help_text='Required. Enter a unique ID number (digits only).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must contain only digits', regex='^[0-9]+$')]),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_level',
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('BRANCH_MANAGER', 'Branch Manager'), ('USER', 'User')], max_length=15)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Membership',
                'verbose_name_plural': 'Company Memberships',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
