# Generated by Django 5.0.4 on 2025-06-25 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_item_category_fk_item_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category_fk',
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(help_text='The Developer who owns this company profile.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='global_user_level',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('MEMBER', 'Member')], default='MEMBER', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='api.category'),
        ),
    ]
