# Generated by Django 5.0.4 on 2025-06-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_item_category_fk_alter_company_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='original_stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Original stock quantity when item was created'),
        ),
    ]
