# Generated by Django 5.0.4 on 2025-06-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_item_original_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAW', 'Withdraw'), ('RETURN', 'Return'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ADD_STOCK', 'Add Stock'), ('REMOVE_STOCK', 'Remove Stock')], max_length=20),
        ),
    ]
