# Generated by Django 5.0.4 on 2025-06-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_company_logo_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos/'),
        ),
    ]
