# Generated by Django 5.0.4 on 2025-06-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_company_contact_info_company_email_company_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('SUPERVISOR', 'Supervisor'), ('BRANCH_MANAGER', 'Branch Manager'), ('USER', 'User')], max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAW', 'Withdraw'), ('RETURN', 'Return')], max_length=10),
        ),
    ]
