# Generated by Django 5.0.4 on 2025-07-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_customuser_profile_picture_remove_item_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Unique reference number for this transaction', max_length=20, null=True, unique=True),
        ),
    ]
