# Generated by Django 5.0.4 on 2025-07-04 01:13

from django.db import migrations
import uuid
import datetime

def populate_reference_numbers(apps, schema_editor):
    Transaction = apps.get_model('api', 'Transaction')
    for transaction in Transaction.objects.filter(reference_number__isnull=True):
        date_str = transaction.timestamp.strftime('%Y%m%d') if transaction.timestamp else datetime.datetime.now().strftime('%Y%m%d')
        unique_part = str(uuid.uuid4())[:8]
        transaction.reference_number = f"TRX{date_str}-{unique_part}"
        transaction.save(update_fields=["reference_number"])

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0030_transaction_reference_number'),
    ]

    operations = [
        migrations.RunPython(populate_reference_numbers, reverse_code=migrations.RunPython.noop),
    ]
