# Generated by Django 5.0.4 on 2025-07-04 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_populate_reference_numbers'),
    ]

    operations = [
    ]
