# Generated by Django 5.0.4 on 2025-07-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_populate_reference_numbers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('branch', 'barcode_number')},
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode_number',
            field=models.CharField(blank=True, help_text='Barcode number (can be different from item_id)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(blank=True, help_text='Auto-generated unique item ID', max_length=50, null=True, unique=True),
        ),
    ]
