# Generated by Django 5.0.4 on 2025-07-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_branch_to_transaction'),
        ('api', '0034_add_branch_is_active'),
    ]

    operations = [
    ]
